return {
  { name = "batman", repo = "brycetolman54/batman", setup = true },
  { name = "plenary", repo = "nvim-lua/plenary.nvim", setup = false },
  { name = "plenary1", repo = "nv-lua/plenary.nvim", setup = false },
  { name = "plenary2", repo = "nv-lua/plenary.nvim", setup = false },
  { name = "plenary3", repo = "nv-lua/plenary.nvim", setup = false },
  { name = "plenary4", repo = "nv-lua/plenary.nvim", setup = false },
  { name = "gruvbox", repo = "morhetz/gruvbox", setup = true },
  { name = "whichkey", repo = "folke/which-key.nvim", setup = true },
  { name = "noice", repo = "folke/noice.nvim", setup = true },
  { name = "nui", repo = "MunifTanjim/nui.nvim", setup = true },
  { name = "notify", repo = "rcarriga/nvim-notify", setup = true },
  { name = "lualine", repo = "nvim-lualine/lualine.nvim", setup = true },
  { name = "barbar", repo = "romgrk/barbar.nvim", setup = true },
  { name = "dev-icons", repo = "nvim-tree/nvim-web-devicons", setup = false },
}
